# Generated by Django 2.1.5 on 2019-02-09 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20190209_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 17, 32, 41, 89567, tzinfo=utc), verbose_name='Date added'),
        ),
    ]
